version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12

    pre_build:
        commands:
            - echo Installing dependencies...
            - npm ci
    build:
        commands:
            - echo Buiilding...
            - npm run build:prod
    post_build:
        commands:
            - echo Build complete on `date`

artifacts:
    files:
        - '**/*'

    base-directory: dist
